services:
  db:
    image: mongo
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb
    ports:
      - "127.0.0.1:27017:27017"
    secrets:
      - db_password

  api:
    depends_on:
      - db
    build: .
    ports:
      - "127.0.0.1:8000:80"
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      SECRET: /run/secrets/hmac
    secrets:
      - hmac

secrets:
   db_password:
     file: secrets/db_password.txt
   hmac:
     file: secrets/hmac.txt

volumes:
    db_config:
    db_data:
