services:
  db:
    image: mongo
    hostname: mongo
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb
    ports:
      - "127.0.0.1:27017:27017"

  db-management:
    image: mongo-express
    ports:
      - "127.0.0.1:8081:8081"
    depends_on:
      - db

volumes:
    db_config:
    db_data:
