services:
  db:
    image: mongo
    hostname: mongo
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb

  api:
    depends_on:
      - db
    build: server/
    ports:
      - "127.0.0.1:8263:3000"
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      JWT_SECRET: /run/secrets/hmac
      MONGO_HOST: db
      SPTF: /run/secrets/spotify
      SPTF_SECRET: /run/secrets/spotify_secret
      BASE_URL: /api
    secrets:
      - hmac

secrets:
   hmac:
     file: secrets/hmac.txt
   spotify:
     file: secrets/spotify.txt
   spotify_secret:
     file: secrets/spotify_secret.txt

volumes:
    db_config:
    db_data:
