services:
  reactapp:
    build: client/
    ports:
      - "127.0.0.1:8265:80"

  db:
    image: mongo
    hostname: mongodbms
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb

  api:
    depends_on:
      - db
    build: server/
    ports:
      - "127.0.0.1:8263:3000"
    env_file:
      - .env
    restart: always
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      MONGO_HOST: mongodbms
      BASE_URL: /api
      REDIRECT_HOST: "https://spotimeet.fedele.website/api"

  db-management:
    image: mongo-express
    ports:
      - "127.0.0.1:8264:8081"
    environment:
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_URL: mongodb://mongodbms:27017/spotimeet
      ME_CONFIG_SITE_BASEURL: /mongo/
    depends_on:
      - db

  swagger:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "127.0.0.1:8267:8080"
    volumes:
      - ./server/swagger.json:/app/swagger.json
    environment:
      BASE_URL: "/swagger"

volumes:
    db_config:
    db_data:
